### ISSUE TITLE
message事件监听器超过最大数量问题

### ISSUE THREAD

**Issue by lgyHector** [node-weixin/node-weixin-message#5]
在使用关注事件监听方法时候，进行了3次以上关注、取消关注操作后，抛出监听器超过最大数量异常

``` js
 messages.event.on.subscribe(function(msg){
        console.log('---关注----')
    });
```

(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
  at EventEmitter.addListener (events.js:160:15)
  at EventEmitter.once (events.js:185:8)

**Comment by calidion** [comment]
solved by https://github.com/node-weixin/node-weixin-message/commit/580fbecc0619c2997b2a38cf87ec6c248d225cd8
